/**
 * data.js -- loads the catalog generated by tools/extract-workbook.ps1.
 *
 * Everything here is read-only reference data that ships with the app. User
 * data (1RMs, sessions, log) lives in store.js and is never mixed in, so
 * re-extracting the workbook can't destroy anyone's history.
 *
 * Two things are folded in on top of the generated files:
 *
 *   - data/hypertrophy.json, the fourth goal. It is hand-authored, because
 *     the workbook only prescribes three, and the extractor rewrites
 *     prescriptions.json and vocabulary.json wholesale every time it runs.
 *     Merging it here means the goal survives a re-extract.
 *
 *   - data/conditioning.json, the HIIT movements and the pace overlay. Same
 *     reasoning again: the compendium is a lifting compendium and has no idea
 *     what a calorie or an AMRAP is.
 *
 *   - the user's own exercises, via `withCustomExercises`. That one takes the
 *     list as an argument rather than reading storage, so this file still has
 *     no idea store.js exists and the reference/user split holds.
 */

import { indexPrescriptions, indexComplexity } from './engine.js';

const FILES = [
  'exercises',
  'warmups',
  'mobility',
  'prescriptions',
  'vocabulary',
  'hypertrophy',
  'complexity',
  'conditioning',
];

/**
 * Where the fourth goal sits in the list.
 *
 * Appending it would have been less code, but the goals read as an intensity
 * continuum everywhere they are listed -- Explosive, Strength, Hypertrophy,
 * Endurance -- and a goal bolted onto the end reads as an afterthought rather
 * than as a point on that line.
 */
const HYPERTROPHY = 'Hypertrophy';
const HYPERTROPHY_AFTER = 'Strength';

async function loadJson(name) {
  const res = await fetch(`data/${name}.json`, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Could not load data/${name}.json (${res.status})`);
  return res.json();
}

/**
 * The workbook's selection formulas tie-break on library row number (`n` in
 * `priority * 1000 + n`), so stamp each item with its 1-based position. JSON
 * preserves array order, so this matches the sheet exactly.
 */
function withRowNumbers(items) {
  return items.map((item, i) => ({ ...item, row: i + 1 }));
}

function goalsWithHypertrophy(goals) {
  if (goals.includes(HYPERTROPHY)) return goals;
  const at = goals.indexOf(HYPERTROPHY_AFTER);
  const out = goals.slice();
  out.splice(at < 0 ? out.length : at + 1, 0, HYPERTROPHY);
  return out;
}

/**
 * Conditioning movements become ordinary catalog rows.
 *
 * They have to: a log entry refers to an exercise id, the warm-up builder reads
 * `pattern` and `secondary` off whatever is in the session, and the "how to do
 * it" panel wants the same `how` field a mobility drill has. Giving them their
 * own parallel catalog would mean teaching every one of those about a second
 * kind of exercise.
 *
 * `mode: 'conditioning'` is what keeps them out of the places they do not
 * belong -- the Library, the Build picker, the quick-workout generator -- all
 * of which want lifts. Rows without the field are lifting rows, so nothing that
 * already exists has to be touched.
 */
const CONDITIONING = 'conditioning';

function asExerciseRows(movements) {
  return movements.map((m) => ({ ...m, mode: CONDITIONING }));
}

export async function loadCatalog() {
  const [exercises, warmups, mobility, prescriptions, vocabulary, hypertrophy, complexity, conditioning] =
    await Promise.all(FILES.map(loadJson));

  const prescriptionItems = [...prescriptions.items, ...hypertrophy.items];

  return finish({
    complexity,
    conditioning,
    exercises: [...exercises.items, ...asExerciseRows(conditioning.movements)],
    warmups: withRowNumbers(warmups.items),
    mobility: withRowNumbers(mobility.items),
    prescriptions: prescriptionItems,
    setupSeconds: prescriptions.setupSecondsPerExercise,
    vocabulary: { ...vocabulary, goals: goalsWithHypertrophy(vocabulary.goals) },
    generated: exercises.meta?.generated ?? null,
  });
}

/**
 * The parts derived from the exercise list, recomputed whenever that list
 * changes -- which is every time the user adds, edits or deletes one of their
 * own exercises.
 */
function finish(catalog) {
  const byId = new Map(catalog.exercises.map((ex) => [ex.id, ex]));
  const paces = catalog.conditioning?.paces || {};
  const tierOf = indexComplexity(catalog.complexity);

  /**
   * How this exercise is measured in a conditioning block, or null if it has
   * no business in one.
   *
   * Two sources, one answer. A native conditioning movement carries its own
   * unit and pace; an exercise the compendium already had gets them from the
   * `paces` overlay, because a Thruster does not need a second catalog row --
   * it needs a second way of being prescribed. Anything in neither is not
   * pickable for conditioning, which is the right default when most of the
   * catalog is loaded barbell work.
   */
  function conditioningOf(exercise) {
    if (!exercise) return null;
    const own = exercise.mode === CONDITIONING;
    const overlay = paces[exercise.name?.en ?? exercise.name];
    if (!own && !overlay) return null;
    const src = own ? exercise : overlay;
    return {
      unit: src.unit,
      /** Units per minute at a hard but repeatable effort. See the data file. */
      pace: src.pace,
      kit: src.kit,
      impact: src.impact || 'low',
      tier: tierOf(exercise),
      native: own,
    };
  }

  return {
    ...catalog,
    byId,
    prescriptionIndex: indexPrescriptions(catalog.prescriptions),
    /** Skill tier for any exercise, the user's own included. See §18. */
    tierOf,
    conditioningOf,
    /** Everything pickable for a conditioning block, lifts and movements alike. */
    conditioningPool: catalog.exercises.filter((ex) => conditioningOf(ex)),
    /** The lifting catalog: what the Library, the picker and Quick workout mean. */
    liftingPool: catalog.exercises.filter((ex) => ex.mode !== CONDITIONING),
    /**
     * Exercise ids are numbers in the shipped catalog and strings ('u3') for
     * the user's own, so anything that has been through a `value` attribute or
     * a URL comes back as text and has to be resolved rather than parsed.
     * Returns null for an id that no longer exists.
     */
    resolveId(raw) {
      if (byId.has(raw)) return raw;
      const n = Number(raw);
      return Number.isFinite(n) && byId.has(n) ? n : null;
    },
  };
}

/**
 * The shipped catalog plus the user's own exercises.
 *
 * The customs go last so a user exercise can never displace a workbook one in
 * the library ordering, and so `row`-style tie-breaks -- which the warm-up and
 * cool-down selection depend on -- are untouched by anything the user adds.
 */
export function withCustomExercises(catalog, customs = []) {
  const base = catalog.baseExercises ?? catalog.exercises;
  return finish({ ...catalog, baseExercises: base, exercises: [...base, ...customs] });
}
