/**
 * data.js -- loads the catalog generated by tools/extract-workbook.ps1.
 *
 * Everything here is read-only reference data that ships with the app. User
 * data (1RMs, sessions, log) lives in store.js and is never mixed in, so
 * re-extracting the workbook can't destroy anyone's history.
 */

import { indexPrescriptions } from './engine.js';

const FILES = ['exercises', 'warmups', 'mobility', 'prescriptions', 'vocabulary'];

async function loadJson(name) {
  const res = await fetch(`data/${name}.json`, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Could not load data/${name}.json (${res.status})`);
  return res.json();
}

/**
 * The workbook's selection formulas tie-break on library row number (`n` in
 * `priority * 1000 + n`), so stamp each item with its 1-based position. JSON
 * preserves array order, so this matches the sheet exactly.
 */
function withRowNumbers(items) {
  return items.map((item, i) => ({ ...item, row: i + 1 }));
}

export async function loadCatalog() {
  const [exercises, warmups, mobility, prescriptions, vocabulary] = await Promise.all(
    FILES.map(loadJson)
  );

  const exerciseItems = exercises.items;
  const byId = new Map(exerciseItems.map((ex) => [ex.id, ex]));

  return {
    exercises: exerciseItems,
    byId,
    warmups: withRowNumbers(warmups.items),
    mobility: withRowNumbers(mobility.items),
    prescriptions: prescriptions.items,
    prescriptionIndex: indexPrescriptions(prescriptions.items),
    setupSeconds: prescriptions.setupSecondsPerExercise,
    vocabulary,
    generated: exercises.meta?.generated ?? null,
  };
}
